packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  sharp: true
  unrs-resolver: false

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - argon2
  - esbuild
  - prisma
  - sharp
